version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5432"]
      interval: 30s
      timeout: 10s
      retries: 5
  backend:
    build:
      context: ./backend/
    env_file: .env
    restart: on-failure
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend/
    ports:
      - 3000:3000
    stdin_open: true
    command: npm start
volumes:
  data:
